name 'base'
maintainer 'Fleet Operations'
maintainer_email 'ops@fleet.example'
license 'Apache-2.0'
description 'Base configuration applied to all fleet nodes'
version '0.4.0'
chef_version '>= 18.0'

recipe 'base', 'Base configuration: packages, deploy user, ssh, motd'
recipe 'base::nginx', 'Nginx web server on port 80 (fleet-01)'
recipe 'base::apache_freshrss', 'Apache2 + FreshRSS RSS reader on port 80 (fleet-02)'
recipe 'base::apache_rssbridge', 'Apache2 + RSS-Bridge on port 80 (fleet-03)'
recipe 'base::glance', 'Glance dashboard on port 8080 (fleet-04)'
recipe 'base::rsshub', 'RSSHub via Docker on port 1200 (fleet-05)'
recipe 'base::miniflux', 'Miniflux RSS reader on port 8080 (fleet-06)'
