name 'base'
maintainer 'Fleet Operations'
maintainer_email 'ops@fleet.example'
license 'Apache-2.0'
description 'Base configuration applied to all fleet nodes — single source of truth for packages, users, ssh, motd, and application stack (nginx, apache2, glance, rsshub, miniflux)'
version '0.3.0'
chef_version '>= 18.0'

recipe 'base', 'Base configuration: packages, deploy user, ssh, motd'
recipe 'base::nginx', 'Nginx web server on port 80'
recipe 'base::apache2', 'Apache2 + PHP web server on port 80'
recipe 'base::glance', 'Glance dashboard on port 8080'
recipe 'base::rsshub', 'RSSHub (Docker) on port 1200'
recipe 'base::miniflux', 'Miniflux RSS reader on port 8080'
