[package]
name = "spindle-obs"
version.workspace = true
edition = "2021"

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
uuid = { version = "1", features = ["v4", "v7", "serde"] }
axum = { workspace = true }
tower = { workspace = true }
serde = { workspace = true }
regex = "1"
