[package]
name = "spindle-identity"
version.workspace = true
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
spindle-dex = { path = "../spindle-dex", version = "0.2" }
spindle-authz = { path = "../spindle-authz", version = "0.2" }