[package]
name = "spindle-server"
version.workspace = true
edition = "2021"

[dependencies]
tower = { workspace = true }
tokio = { workspace = true }
axum = { version = "0.7", features = ["macros"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
figment = { workspace = true }
clap = { workspace = true }
thiserror = { workspace = true }
sqlx = { workspace = true }
tempfile = "3.10"
subtle = { workspace = true }
hex = { workspace = true }
chrono = { workspace = true }
sha2 = { workspace = true }
governor = { workspace = true }
jsonwebtoken = "9"
argon2 = { workspace = true }

spindle-rawarchive = { path = "../spindle-rawarchive" }
spindle-api = { path = "../spindle-api" }
spindle-store = { path = "../spindle-store" }
spindle-authz = { path = "../spindle-authz" }
spindle-dex = { path = "../spindle-dex" }
spindle-saml = { path = "../spindle-saml" }
spindle-signing = { path = "../spindle-signing" }
async-trait = { workspace = true }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
tokio = { version = "1.36", features = ["full", "test-util"] }
