[package]
name = "spindle-server"
version.workspace = true
edition = "2021"

[dependencies]
tower = { workspace = true }
tokio = { workspace = true }
axum = { version = "0.7", features = ["macros"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
figment = { workspace = true }
clap = { workspace = true }
thiserror = { workspace = true }
sqlx = { workspace = true }
tempfile = "3.10"
subtle = { workspace = true }
hex = { workspace = true }
chrono = { workspace = true }
sha2 = { workspace = true }
governor = { workspace = true }
jsonwebtoken = "9"
argon2 = { workspace = true }
ldap3 = { workspace = true }
reqwest = { workspace = true }
base64 = "0.22"
rand = "0.8"
axum-server = { version = "0.7", default-features = false, optional = true }
rustls = { version = "0.23", default-features = false, features = ["std", "ring"], optional = true }
rustls-pemfile = { version = "2", optional = true }

spindle-rawarchive = { path = "../spindle-rawarchive" }
spindle-config = { path = "../spindle-config" }
spindle-api = { path = "../spindle-api" }
spindle-store = { path = "../spindle-store" }
spindle-authz = { path = "../spindle-authz" }
spindle-signing = { path = "../spindle-signing" }
spindle-dex = { path = "../spindle-dex" }
spindle-saml = { path = "../spindle-saml" }
spindle-pipeline = { path = "../spindle-pipeline" }
async-trait = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }

[dev-dependencies]
tokio = { version = "1.36", features = ["full", "test-util"] }
toml = "0.8"

[features]
default = []
tls = ["axum-server/tls-rustls", "dep:axum-server", "dep:rustls", "dep:rustls-pemfile"]

[[bin]]
name = "spindle-server"
path = "src/main.rs"
