[package]
name = "spindle-server"
version.workspace = true
edition = "2021"

[dependencies]
tower = { workspace = true }
tokio = { workspace = true }
axum = { version = "0.7", features = ["macros", "query"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
figment = { workspace = true }
clap = { workspace = true }
thiserror = { workspace = true }
sqlx = { workspace = true }
tempfile = "3.10"
subtle = { workspace = true }
hex = { workspace = true }
chrono = { workspace = true }
sha2 = { workspace = true }
argon2 = { workspace = true }
governor = { workspace = true }
openidconnect = { version = "3", features = ["reqwest"] }
jsonwebtoken = { workspace = true }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
time = { workspace = true }
rand = "0.8"
base64 = "0.22"
percent-encoding = "2.3"

spindle-rawarchive = { path = "../spindle-rawarchive" }
spindle-api = { path = "../spindle-api" }
spindle-store = { path = "../spindle-store" }
spindle-authz = { path = "../spindle-authz" }
spindle-identity = { path = "../spindle-identity" }
spindle-dex = { path = "../spindle-dex" }
async-trait = { workspace = true }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
