[package]
name = "spindle-migrate"
version.workspace = true
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
sqlx = { workspace = true }
clap = { workspace = true, features = ["env"] }

[[bin]]
name = "spindle-migrate"
path = "src/main.rs"
