/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CookbooksIndexRouteImport } from './routes/cookbooks.index'
import { Route as CookbooksNameRouteImport } from './routes/cookbooks.$name'
import { Route as NodesIndexRouteImport } from './routes/nodes.index'
import { Route as NodesNodeIdRouteImport } from './routes/nodes.$nodeId'
import { Route as ProfilesIndexRouteImport } from './routes/profiles.index'
import { Route as ProfilesProfileIdRouteImport } from './routes/profiles.$profileId'
import { Route as RunsIndexRouteImport } from './routes/runs.index'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/__spindle-admin/settings',
  path: '/__spindle-admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbooksIndexRoute = CookbooksIndexRouteImport.update({
  id: '/cookbooks/',
  path: '/cookbooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbooksNameRoute = CookbooksNameRouteImport.update({
  id: '/cookbooks/$name',
  path: '/cookbooks/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesIndexRoute = NodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesNodeIdRoute = NodesNodeIdRouteImport.update({
  id: '/nodes/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIndexRoute = ProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesProfileIdRoute = ProfilesProfileIdRouteImport.update({
  id: '/profiles/$profileId',
  path: '/profiles/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/__spindle-admin/settings': typeof SettingsRoute
  '/cookbooks/$name': typeof CookbooksNameRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/cookbooks/': typeof CookbooksIndexRoute
  '/nodes/': typeof NodesIndexRoute
  '/profiles/': typeof ProfilesIndexRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/__spindle-admin/settings': typeof SettingsRoute
  '/cookbooks/$name': typeof CookbooksNameRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/cookbooks': typeof CookbooksIndexRoute
  '/nodes': typeof NodesIndexRoute
  '/profiles': typeof ProfilesIndexRoute
  '/runs': typeof RunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/__spindle-admin/settings': typeof SettingsRoute
  '/cookbooks/$name': typeof CookbooksNameRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/cookbooks/': typeof CookbooksIndexRoute
  '/nodes/': typeof NodesIndexRoute
  '/profiles/': typeof ProfilesIndexRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance'
    | '/__spindle-admin/settings'
    | '/cookbooks/$name'
    | '/nodes/$nodeId'
    | '/profiles/$profileId'
    | '/runs/$runId'
    | '/cookbooks/'
    | '/nodes/'
    | '/profiles/'
    | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/__spindle-admin/settings'
    | '/cookbooks/$name'
    | '/nodes/$nodeId'
    | '/profiles/$profileId'
    | '/runs/$runId'
    | '/cookbooks'
    | '/nodes'
    | '/profiles'
    | '/runs'
  id:
    | '__root__'
    | '/'
    | '/compliance'
    | '/__spindle-admin/settings'
    | '/cookbooks/$name'
    | '/nodes/$nodeId'
    | '/profiles/$profileId'
    | '/runs/$runId'
    | '/cookbooks/'
    | '/nodes/'
    | '/profiles/'
    | '/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplianceRoute: typeof ComplianceRoute
  SettingsRoute: typeof SettingsRoute
  CookbooksNameRoute: typeof CookbooksNameRoute
  NodesNodeIdRoute: typeof NodesNodeIdRoute
  ProfilesProfileIdRoute: typeof ProfilesProfileIdRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  CookbooksIndexRoute: typeof CookbooksIndexRoute
  NodesIndexRoute: typeof NodesIndexRoute
  ProfilesIndexRoute: typeof ProfilesIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__spindle-admin/settings': {
      id: '/__spindle-admin/settings'
      path: '/__spindle-admin/settings'
      fullPath: '/__spindle-admin/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbooks/': {
      id: '/cookbooks/'
      path: '/cookbooks'
      fullPath: '/cookbooks/'
      preLoaderRoute: typeof CookbooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbooks/$name': {
      id: '/cookbooks/$name'
      path: '/cookbooks/$name'
      fullPath: '/cookbooks/$name'
      preLoaderRoute: typeof CookbooksNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/': {
      id: '/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof NodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/$nodeId': {
      id: '/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/nodes/$nodeId'
      preLoaderRoute: typeof NodesNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/': {
      id: '/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof ProfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$profileId': {
      id: '/profiles/$profileId'
      path: '/profiles/$profileId'
      fullPath: '/profiles/$profileId'
      preLoaderRoute: typeof ProfilesProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplianceRoute: ComplianceRoute,
  SettingsRoute: SettingsRoute,
  CookbooksNameRoute: CookbooksNameRoute,
  NodesNodeIdRoute: NodesNodeIdRoute,
  ProfilesProfileIdRoute: ProfilesProfileIdRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  CookbooksIndexRoute: CookbooksIndexRoute,
  NodesIndexRoute: NodesIndexRoute,
  ProfilesIndexRoute: ProfilesIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
