[package]
name = "spindle-mcp"
version.workspace = true
edition = "2021"

[lib]
name = "spindle_mcp"
path = "src/lib.rs"

[[bin]]
name = "spindle-mcp"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
mcp-server = { path = "../mcp-server" }
spindle-cli = { path = "../spindle-cli" }
uuid = { workspace = true }
