[package]
name = "spindle-mcp"
version.workspace = true
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "spindle_mcp"
path = "src/lib.rs"

[[bin]]
name = "spindle-mcp"
path = "src/main.rs"

[dependencies]
spindle-obs = { path = "../spindle-obs" }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
mcp-server = { path = "../mcp-server", version = "0.2" }
spindle-cli = { path = "../spindle-cli", version = "0.2" }
uuid = { workspace = true }
