[package]
name = "spindle-cli"
version.workspace = true
edition = "2021"

[lib]
name = "spindle_cli"
path = "src/lib.rs"

[[bin]]
name = "spindle"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["env"] }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
toml = "0.8"
spindle-config = { path = "../spindle-config" }
spindle-signing = { path = "../spindle-signing" }
ed25519-dalek = { version = "3.0", features = ["rand_core"] }
signature = "3"
base64 = "0.21"
walkdir = "2"
flate2 = "1"
hex = "0.4"
tabled = "0.18"

[dev-dependencies]
clap = { version = "4", features = ["derive", "env", "debug"] }
tempfile = "3"